tensorboard:
  run_id: "medium_test"
wandb:
  enabled: true
  run_id: "medium_test"
  project: "rl_final"
  sync_tensorboard: true

train:
  algorithm: "PPO"
  policy_network: "MlpPolicy"
  save_path: "model/medium_test"
  num_train_envs: 4
  epoch_num: 100
  timesteps_per_epoch: 1024
  eval_episode_num: 5
  batch_size: 4
  n_steps: 512
  data_root: "data/GOT10_medium/train"
  stack: 3
  action_repeat: 32
  encoder: "ResNet18"

valid:
  data_root: "data/GOT10_medium/val"

visualize:
  index: [1]