tensorboard:
  run_id: "medium_test_time_tiny_1"
wandb:
  enabled: true
  run_id: "medium_test_time_tiny_1"
  project: "rl_final"
  sync_tensorboard: true

train:
  algorithm: "PPO"
  policy_network: "MlpPolicy"
  save_path: "model/medium_test_time_tiny_1"
  num_train_envs: 1
  epoch_num: 2
  timesteps_per_epoch: 4
  eval_episode_num: 1
  batch_size: 2
  n_steps: 2
  data_root: "data/GOT10_medium/train"
  stack: 3
  action_repeat: 32
  encoder: "ResNet18"

valid:
  data_root: "data/GOT10_medium/val"

visualize:
  index: [1]